### ISSUE TITLE
Make release tag "v.2.10.0" for GIMP 2.10 official release

### ISSUE THREAD

**Issue by ghost** [aferrero2707/gimp-appimage#10]
*GIMP 2.10* officially released!

- https://www.gimp.org/release-notes/gimp-2.10.html
  - https://download.gimp.org/mirror/pub/gimp/v2.10/

### TODO

- [ ] https://github.com/aferrero2707/gimp-appimage/releases/tag/v2.10.0
  - [ ] https://github.com/aferrero2707/gimp-appimage/releases/download/v2.10.0/gimp-2.10.0-glibc2.15-x86_64.AppImage

**Comment by aferrero2707** [comment]
Unfortunately the build configuration for 2.10.0 is "broken", in the sense that GIMP requires gegl-0.4 but reports a dependency on gegl-0.3 in its pkgconfig file.

As a consequence, installation of plugins which rely on `gimp-2.0.pc` for finding GIMP and its dependencies fail because of the missing `gegl-0.3.pc` file

**Comment by aferrero2707** [comment]
I am closing this, the packaging of the official release is postponed until 2.10.2 is out.
