### ISSUE TITLE
GIMP 2.10.6 (Half the size - Missing Gmic-Qt)

### ISSUE THREAD

**Issue by dCo3lh0** [aferrero2707/gimp-appimage#18]
Hi, i noticed the last GIMP Appimage had half of the default general size, so i looked into it, it's missing Gmic-Qt, anyways thanks for the new release.

**Comment by aferrero2707** [comment]
@dCo3lh0 the latest AppImage is experimental, since I changed the build environment (moved from Ubuntu 14.04 to CentOS 7).

Now that the GIMP part seems to work properly, I will add back the plug-ins. I am also looking for a way to implement the plug-ins as a separate package, but that's not for tomorrow...

**Comment by aferrero2707** [comment]
GIMP AppImages with GMIC-Qt are now available. Please download the latest package that is labelled  `-withplugins`.

Closing
