### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [aferrero2707/gimp-appimage#2]
Does not run on Ubuntu 14.04 because `libexiv2.so.26` depends on a too new `libstdc++.so.6`:

```
bin/gimp.bin: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ././/lib/libexiv2.so.26)
```

This currently prevents GIMP from being added to the AppImageHub central directory of available AppImages.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/282749650#L912

**Comment by aferrero2707** [comment]
Quite strange... I am producing the AppImage on a Linux Mint 17.2 system, which is based on Ubuntu 14.04.

Would you be able to provide me the output of

    strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC

from the system in which the AppImage is being tested? On Mint 17.2, the GLIBCXX versions are listed up to 3.4.23.

Otherwise, I will probably need to move my build system to an "original" Ubuntu 14.04...

**Comment by probonopd** [comment]
I am using the Ubuntu 14.04 on Travis CI. Could you build your AppImage on Travis CI, too?

**Comment by aferrero2707** [comment]
@probonopd - the AppImage is now built in a Ubuntu 14.04 docker container running on Travis CI.

Could you please test the latest version from [here](https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/gimp-2.10.0-20180403_1029.glibc2.15-x86_64.AppImage), and let me know if you encounter any problems? Otherwise I would close this issue.

Thanks!

**Comment by probonopd** [comment]
Thank you, works for me now. Already added to AppImageHub, too :-)
