### ISSUE TITLE
no more gimp with plugins releases?

### ISSUE THREAD

**Issue by cuyo01** [aferrero2707/gimp-appimage#34]
the last release of gimp with plugins appimage its from march, im using ubuntu 18.04 but am unable to install/run latest gmic plugin and your release is the only with a working gmic plugin available with a recent gimp release and a recent working gmic plugin.

**Comment by aferrero2707** [comment]
@cuyo01 The plug-ins have not disappeared, they have just been moved to a separate project, to simplify the updating process.

You can get them from here: https://github.com/aferrero2707/gimp-plugins-collection/releases/tag/continuous

The installation instructions are provided in the same release page. I have also updated the README.md in this repository to reflect this change, so that the new way of installing the plug-ins is correctly documented.

One of the main advantages of having separate plug-in packages is that you can for example update G'MIC without having to update/reinstall the main GIMP package...

**Comment by probonopd** [comment]
One thing I __loved__ about this project is that you could download __one__ file and had __everything__, without having to fiddle around, download stuff from multiple places, or installing anything.

Please bring back the "with plugins", "with everything" releases, no matter what the size. (Thanks to AppImageUpdate updating is still as efficient as before.)

**Comment by phd21** [comment]
Hi aferrero2707,

Big +1 for Please bring back the single "AppImage with plugins" rather than having to install 5 more AppImages to get the plugins?

Regards,
Phil (phd21)

**Comment by cuyo01** [comment]
@aferrero2707 
Thanks, I understand that is more easy this metod than compiling everything again when there is only a change in one plugin.

**Comment by aferrero2707** [comment]
@probonopd @phd21 I will re-introduce the "AppImage with plugins" package, but I propose to follow a different approach: the "with plugins" package will be a re-packaging of the barebones AppImage, using the existing plugins from [here](https://github.com/aferrero2707/gimp-plugins-collection/releases/tag/continuous).

That is, the plugins will not be compiled by the GIMP AppImage scripts, because this might easily hit the time limitations for Travis jobs.

What do you think?

**Comment by probonopd** [comment]
Yes, great idea - no need to compile the contents of the AppImage twice. Just `--appimage-extract`, add files, re-pack with `appimagetool -g`.

**Comment by KenLidd** [comment]
Not sure I understand how this differs from the AppImage with Plugins
package of the past?  I personally rather liked the separated approach as
long as any changes to the plugin AppImage files were clearly dated so we
would know when they changed.
Ken

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by aferrero2707** [comment]
@KenLidd in the past, the plugins were compiled together with GIMP each time a new AppImage was created. However, some plugins like GMIC are quite heavy to compile, and this was increasing the Travis job duration excessively.

Moreover, if one wanted to update GMIC, he would be obliged to wait until the next AppImage was built and then download GIMP+all the plugins.

What I am proposing here is to have a separate job that fetches the latest GIMP AppImage and all the available plugins, and re-packages them into a single AppImage.

@probonopd @phd21: an alternative approach would be to add a `--install-plugins` option to the GIMP AppImage than would take care of downloading and installing the available plugins... that would be much easier to implement, and would not require an additional packaging step.

**Comment by probonopd** [comment]
I like the fact that everything is contained in one file, which can be used on offline machines with no additional downloading of stuff.

**Comment by phd21** [comment]
Hi aferrero2707,

Thank you for your replies and attention to this. 

I think the last option you mention "add a --install-plugins option" that would automatically download and install the plugins would work too. Still not sure what's wrong with just including them in the AppImage with plugins and perhaps installing them rather than using the "tmp" folder. Although certain plugins like GMIC may take a while to compile, isn't that done automatically using your AppImage scripts?

I am a little confused about the reasoning with plugins like GMIC. If the GMIC or other plugins were installed in the typical AppImage way under the user configuration AppImage folder, how would users updating, let's say the GMIC plugin with a newer version, do that except manually? If you update the GMIC plugin from the Software Manager or Synaptic Package Manager (SPM) or the Gimp PPA, would not the users still have to manually copy the newly updated plugin file(s) to the user AppImage configuration plugins folder?

Thank you again for providing these Gimp AppImages and plugins very nice and thoughtful of you and very much appreciated by a lot of people. 

Best regards,
Phil (phd21)
phd21mint@gmail.com

**Comment by KenLidd** [comment]
Understand - I think whatever is less work for you would be the preferred
route here - the end result from our perspective will be the same.
Appreciate all that you do.
Ken
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by probonopd** [comment]
> I am a little confused about the reasoning with plugins like GMIC. If the GMIC or other plugins were installed in the typical AppImage way under the user configuration AppImage folder, how would users updating, let's say the GMIC plugin with a newer version, do that except manually?

In case the extensions come as part of the AppImage and are loaded from there (without being copied around in the system):
Update the whole AppImage, which also updates the plugins included therein. Using AppImageUpdate binary delta updates, only a few MB would have to be downloaded since the bulk of the AppImage would remain unchanged from version to version.

**Comment by aferrero2707** [comment]
It is definitely time for me to look into AppImageUpdate! Will work on the GIMP AppImage repackaging during the next days, and post here about the progresses...

**Comment by probonopd** [comment]
A GTK UI for `libappimageupdate` would be neat ;-)

**Comment by aferrero2707** [comment]
@cuyo01 @phd21 @KenLidd @probonopd 
The AppImage packages with bundled plugins are back! Please give me some feedback if things work properly for you, or if you notice any issues...

**Comment by KenLidd** [comment]
Just downloaded and opened the combined AppImage and all looks good so far
- plugins appear to be accessible.  will be doing more extensive testing
later in the week. Much appreciated.
Ken

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by aferrero2707** [comment]
Thanks for checking @KenLidd!

**Comment by aferrero2707** [comment]
I am closing this issue since the package with plugins is available again.
Please open a new issue in case you find problems with the plugins.

**Comment by probonopd** [comment]
Thanks for making this @aferrero2707 :+1:
