### ISSUE TITLE
git-2.99.1-20200625-withplugins-x86_64.AppImage crash

### ISSUE THREAD

**Issue by stevelcb** [aferrero2707/gimp-appimage#54]
Hi everyone
Crash with new version.
To reproduce:
Open a .jpg and hit Colour -> Levels

Cheers

log: https://drive.google.com/file/d/16UFztgjf0MtVEjWjYICWGbyoPBynahIx/view?usp=sharing

**Comment by KenLidd** [comment]
I just checked this and I have no problem nor crash with Ubuntu 18.04 and
the 2.99.1-20200625 AppImage when I open a jpg image and use the
Color-Levels menu tool.
Regards
Ken

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by aferrero2707** [comment]
@stevelcb if you feel brave enough to do some hacking, here is what I propose to do in order to pin down the icon that seems to be missing:
* grab the [latest AppImage](https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/GIMP_AppImage-git-2.99.1-20200628-withplugins-x86_64.AppImage)
* extract the bundle with the following command:
```
./GIMP_AppImage-git-2.99.1-20200628-withplugins-x86_64.AppImage --appimage-extract
```
* make sure the `strace` command is available in your system. If not, it can be installed with
```
sudo apt-get install strace
```
* edit the `squashfs-root/AppRun` text file, and replace the line 93:
```
$DIR/usr/bin/gimp.wrapper --pdb-compat-mode=on "$@"
```
by
```
strace -e trace=open,read $DIR/usr/bin/gimp.bin --pdb-compat-mode=on "$@"
```
* run the `AppRun` script and save the terminal output:
```
squashfs-root/AppRun >& /tmp/gimp-log.txt
```
* reproduce the crash and send me the log...

Thanks!

**Comment by aferrero2707** [comment]
@stevelcb this seems to be related: https://wiki.gimp.org/wiki/Hacking:Problems_and_solutions#On_Ubuntu:_Gtk:ERROR:...2F...2F...2F...2Fgtk.2Fgtkiconhelper.c:494:ensure_surface_for_gicon:_assertion_failed_.28error_.3D.3D_NULL.29:_Icon_.27image-missing.27_not_present_in_theme_Symbolic_.28gtk-icon-theme-error-quark.2C_0

Could you check if the `gnome-icon-theme` is installed in your system, and if not could you try to install it and check again?

Thanks!

**Comment by stevelcb** [comment]
Hey, yeah.

It now works. Thanks so much for your effort on this excellent appimage.

Would it be possible to include:

gnome-icon-theme

in the image?

Cheers,

Steve

**Comment by stevelcb** [comment]
Hi everyone

Just for completeness, I didn't go through this as our packager found 
the missing icon:)

Solution for ubuntu 18.04: install gnome-icon-theme

Cheers and a big thanks for @aferrero2707 for this excellent appimage.

Steve

**Comment by aferrero2707** [comment]
@stevelcb I indeed plan to include the gnome icons into the bundle (see #56), just to avoid this kind of nasty issues that are hard to investigate.
